my_TV=['FBI', 'FBI International', 'FBI Most Wanted', 'Chicago Med', 'Chicago Fire', 'NCIS New Orleans', 'NCIS', 'Equalizer', 'Star Trek: Strange New Worlds']
print(my_TV)
print(my_TV[4])
srt_myTV=sorted(my_TV)
print(srt_myTV)
print(srt_myTV[4])
my_TV.sort(reverse=True)
print(my_TV)
print(my_TV[4])
my_TV.reverse()
print(my_TV)
print(my_TV[4])
